category:
    path:     /
    defaults: { _controller: "BlogBundle:BlogCategory:index" }

category_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:BlogCategory:show" }

category_new:
    path:     /new
    defaults: { _controller: "BlogBundle:BlogCategory:new" }

category_create:
    path:     /create
    defaults: { _controller: "BlogBundle:BlogCategory:create" }
    requirements: { _method: post }

category_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:BlogCategory:edit" }

category_update:
    path:     /{id}/update
    defaults: { _controller: "BlogBundle:BlogCategory:update" }
    requirements: { _method: post|put }

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:BlogCategory:delete" }
    requirements: { _method: post|delete }
